on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Bulid and deploy
    steps:
        - uses: actions/checkout@v3
        - uses: mahmoudgalalz/surge-action@v1.0
          with:
            domain: 'ghtop.surge.sh'
            path: './dist'
            build: |
              pnpm i
              npm run build
          env:
            SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
